---
  enabled_image_drivers:
    vmdk:  True
    qcow2: False
    raw:   False
  image_location:
    directory: '/var/tmp/'
  enabled_backend_drivers:
    ceph: True
    nfs:  False
  credentials:
    openstack:
      # Using the admin's creds and tenant for everything. Change at will.
      authurl:   'http://192.168.80.131:5000/v2.0/tokens'
      tenant:    'admin'
      username:  'admin'
      password:  'password'
